[workspace]
members = [
    "atrium-api",
    "atrium-cli",
    "atrium-repo",
    "atrium-xrpc",
    "atrium-xrpc-client",
]
# Examples show how to use the latest published crates, not the workspace state.
exclude = [
    "examples/concurrent",
    "examples/firehose",
]
resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.70"
repository = "https://github.com/sugyan/atrium"
license = "MIT"
keywords = ["atproto", "bluesky"]

[workspace.dependencies]
# Intra-workspace dependencies
atrium-api = { version = "0.21.2", path = "atrium-api" }
atrium-xrpc = { version = "0.10.6", path = "atrium-xrpc" }
atrium-xrpc-client = { version = "0.5.2", path = "atrium-xrpc-client" }

# async in streams
async-stream = "0.3"

# async in traits
# Can be removed once MSRV is at least 1.75.0.
async-trait = "0.1.68"

# DAG-CBOR codec
ipld-core = { version = "0.4.0", default-features = false, features = ["std"] }
serde_ipld_dagcbor = { version = "0.6.0", default-features = false, features = ["std"] }

# Parsing and validation
chrono = "0.4"
langtag = "0.3"
regex = "1"
serde = "1.0.160"
serde_bytes = "0.11.9"
serde_json = "1.0.96"
serde_html_form = "0.2.6"
unsigned-varint = "0.8"

# Networking
futures = { version = "0.3.30", default-features = false, features = ["alloc"] }
http = "1.1.0"
tokio = { version = "1.36", default-features = false }
tokio-util = "0.7"

# HTTP client integrations
isahc = "1.7.2"
reqwest = { version = "0.12", default-features = false }

# Errors
anyhow = "1.0.80"
thiserror = "1.0"

# CLI
clap = { version = "4.4.18", features = ["derive"] }
dirs = "5.0.1"

# Testing
mockito = "1.4"

# WebAssembly
wasm-bindgen-test = "0.3.41"
